Repository HristianSarmov/3InARow, pull requests merged in 2023-10, with the labels that each got.

#4 Add random image positions on start
  .vscode/settings.json
  project/src/main/java/inarow3/game/InARow3.java
  project/src/main/java/inarow3/game/icons/image-apple.png
  project/src/main/java/inarow3/game/icons/image-banana.png
  project/target/classes/inarow3/game/InARow3.class
Labels: enhancement

#6 Small fixes
  project/src/main/java/inarow3/game/InARow3.java
  project/target/classes/inarow3/game/InARow3.class
  project/target/classes/inarow3/game/icons/image-apple.png
  project/target/classes/inarow3/game/icons/image-banana.png
Labels: bug

#7 Different Image Appearance
  project/src/main/java/inarow3/game/InARow3.java
  project/target/classes/inarow3/game/InARow3.class
Labels: enhancement

#8 Dialog and Design changes
  project/src/main/java/inarow3/game/EndGameDialog.java
  project/src/main/java/inarow3/game/GameRulesDialog.java
  project/src/main/java/inarow3/game/InARow3.java
  project/src/main/java/inarow3/game/icons/gif-crying-pineapple.gif
  project/target/classes/inarow3/game/EndGameDialog.class
  project/target/classes/inarow3/game/GameRulesDialog.class
  project/target/classes/inarow3/game/InARow3.class
  project/target/classes/inarow3/game/icons/gif-crying-pineapple.gif
Labels: enhancement

#9 Basic Functionality Done
  project/src/main/java/inarow3/game/InARow3.java
  project/target/classes/inarow3/game/InARow3.class
Labels: enhancement

#10 Finished Dialogs
  project/src/main/java/inarow3/game/EndGameDialog.java
  project/src/main/java/inarow3/game/GameLevelDialog.java
  project/src/main/java/inarow3/game/GameRulesDialog.java
  project/src/main/java/inarow3/game/StartGameDialog.java
  project/target/classes/inarow3/game/EndGameDialog.class
  project/target/classes/inarow3/game/GameLevelDialog$1.class
  project/target/classes/inarow3/game/GameLevelDialog$2.class
  project/target/classes/inarow3/game/GameLevelDialog$3.class
  project/target/classes/inarow3/game/GameLevelDialog.class
  project/target/classes/inarow3/game/GameRulesDialog$1.class
  project/target/classes/inarow3/game/GameRulesDialog.class
  project/target/classes/inarow3/game/StartGameDialog$1.class
  project/target/classes/inarow3/game/StartGameDialog.class
Labels: enhancement

#11 Freedom-Dialog
  project/src/main/java/inarow3/game/EndGameDialog.java
  project/src/main/java/inarow3/game/FreedomDialog.java
  project/src/main/java/inarow3/game/GameRulesDialog.java
  project/src/main/java/inarow3/game/InARow3.java
  project/src/main/java/inarow3/game/icons/gif-cherry.gif
  project/src/main/java/inarow3/game/icons/gif-freedom.gif
  project/src/main/java/inarow3/game/icons/image-apple.png
  project/src/main/java/inarow3/game/icons/image-banana.png
  project/src/main/java/inarow3/game/icons/image-blueberry.png
  project/src/main/java/inarow3/game/icons/image-cherry.png
  project/src/main/java/inarow3/game/icons/image-grapes.png
  project/src/main/java/inarow3/game/icons/image-kiwi.png
  project/src/main/java/inarow3/game/icons/image-lemon.png
  project/src/main/java/inarow3/game/icons/image-orange.png
  project/src/main/java/inarow3/game/icons/image-pineapple.png
  project/src/main/java/inarow3/game/icons/image-strawberry.png
  project/target/classes/inarow3/game/EndGameDialog$1.class
  project/target/classes/inarow3/game/EndGameDialog$2.class
  project/target/classes/inarow3/game/EndGameDialog.class
  project/target/classes/inarow3/game/FreedomDialog.class
  project/target/classes/inarow3/game/GameRulesDialog$1.class
  project/target/classes/inarow3/game/GameRulesDialog.class
  project/target/classes/inarow3/game/InARow3$1.class
  project/target/classes/inarow3/game/InARow3.class
  project/target/classes/inarow3/game/icons/gif-cherry.gif
  project/target/classes/inarow3/game/icons/gif-freedom.gif
  project/target/classes/inarow3/game/icons/image-apple.png
  project/target/classes/inarow3/game/icons/image-banana.png
  project/target/classes/inarow3/game/icons/image-blueberry.png
  project/target/classes/inarow3/game/icons/image-cherry.png
  project/target/classes/inarow3/game/icons/image-grapes.png
  project/target/classes/inarow3/game/icons/image-kiwi.png
  project/target/classes/inarow3/game/icons/image-lemon.png
  project/target/classes/inarow3/game/icons/image-orange.png
  project/target/classes/inarow3/game/icons/image-pineapple.png
  project/target/classes/inarow3/game/icons/image-strawberry.png
Labels: enhancement

#12 Almost Final Changes
  project/src/main/java/inarow3/game/EndGameDialog.java
  project/src/main/java/inarow3/game/FruitRemovalRueles.java
  project/src/main/java/inarow3/game/GameLevelDialog.java
  project/src/main/java/inarow3/game/GameRulesDialog.java
  project/src/main/java/inarow3/game/InARow3.java
  project/src/main/java/inarow3/game/StartGameDialog.java
  project/src/resources/highscore.properties
  project/target/classes/inarow3/game/EndGameDialog$1.class
  project/target/classes/inarow3/game/EndGameDialog$2.class
  project/target/classes/inarow3/game/EndGameDialog.class
  project/target/classes/inarow3/game/FruitRemovalRueles.class
  project/target/classes/inarow3/game/GameLevelDialog$1.class
  project/target/classes/inarow3/game/GameLevelDialog$2.class
  project/target/classes/inarow3/game/GameLevelDialog$3.class
  project/target/classes/inarow3/game/GameLevelDialog.class
  project/target/classes/inarow3/game/GameRulesDialog.class
  project/target/classes/inarow3/game/InARow3$1.class
  project/target/classes/inarow3/game/InARow3.class
  project/target/classes/inarow3/game/StartGameDialog.class
Labels: bug, enhancement

#13 Final Changes
  project/src/main/java/inarow3/game/EndGameDialog.java
  project/src/main/java/inarow3/game/GameLevelDialog.java
  project/src/main/java/inarow3/game/GameRulesDialog.java
  project/src/main/java/inarow3/game/InARow3.java
  project/src/main/java/inarow3/game/StartGameDialog.java
  project/src/resources/highscore.properties
  project/target/classes/inarow3/game/EndGameDialog$1.class
  project/target/classes/inarow3/game/EndGameDialog$2.class
  project/target/classes/inarow3/game/EndGameDialog.class
  project/target/classes/inarow3/game/GameLevelDialog$1.class
  project/target/classes/inarow3/game/GameLevelDialog$2.class
  project/target/classes/inarow3/game/GameLevelDialog$3.class
  project/target/classes/inarow3/game/GameLevelDialog.class
  project/target/classes/inarow3/game/GameRulesDialog$1.class
  project/target/classes/inarow3/game/GameRulesDialog.class
  project/target/classes/inarow3/game/InARow3$1.class
  project/target/classes/inarow3/game/InARow3.class
  project/target/classes/inarow3/game/StartGameDialog$1.class
  project/target/classes/inarow3/game/StartGameDialog.class
Labels: bug, enhancement
